### ISSUE TITLE
Bug reported in Terminal (production build)

### ISSUE THREAD

**Issue by skiirx** [brillout/vite-plugin-import-build#3]
front | Error: [@brillout/vite-plugin-import-build][Bug] You stumbled upon a bug in the source code of @brillout/vite-plugin-import-build. Reach out at https://github.com/brillout/vite-plugin-import-build/issues/new and include this error stack (the error stack is usually enough to fix the problem). (Debug info for the maintainers: `{"distImporterDir":"/usr/src/app/dist/server","distImporterPathRelative":"/usr/src/app/dist/server/importBuild.cjs"}`)

front |     at assert (/usr/src/app/node_modules/@brillout/vite-plugin-import-build/dist/utils/assert.js:10:11)
front |     at loadWithNodejs (/usr/src/app/node_modules/@brillout/vite-plugin-import-build/dist/loadBuild/index.js:50:32)
front |     at loadBuild (/usr/src/app/node_modules/@brillout/vite-plugin-import-build/dist/loadBuild/index.js:23:51)
front |     at loadBuild (/usr/src/app/node_modules/vite-plugin-ssr/dist/cjs/node/plugin/plugins/importBuild/loadBuild.js:15:72)
front |     at initGlobalContext (/usr/src/app/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/globalContext.js:36:62)
front |     at renderPage (/usr/src/app/node_modules/vite-plugin-ssr/dist/cjs/node/runtime/renderPage.js:22:53)
front |     at file:///usr/src/app/server.js:219:31
front |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
front |     at next (/usr/src/app/node_modules/express/lib/router/route.js:144:13)
front |     at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:114:3)

I was trying to downgrade packages to this versions
"@brillout/vite-plugin-import-build": "0.1.4",
"@brillout/import": "0.2.1"

But the issue still persists :(

**Comment by brillout** [comment]
Update `@brillout/vite-plugin-import-build` to `0.1.11`.

**Comment by brillout** [comment]
You can update `vite-plugin-ssr` to `0.4.78` which will enforce the latest `@brillout/vite-plugin-import-build` version.

I'm assuming this will fix your error, if it doesn't let me know and I'll re-open this ticket.
